Document: wrappy
Title: Debian wrappy Manual
Author: <insert document author here>
Abstract: This manual describes what wrappy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wrappy/wrappy.sgml.gz

Format: postscript
Files: /usr/share/doc/wrappy/wrappy.ps.gz

Format: text
Files: /usr/share/doc/wrappy/wrappy.text.gz

Format: HTML
Index: /usr/share/doc/wrappy/html/index.html
Files: /usr/share/doc/wrappy/html/*.html
